# Generated by Django 3.2.16 on 2022-11-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AlterField(
            model_name='authorbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='parser_books.author'),
        ),
        migrations.AlterField(
            model_name='authorbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='parser_books.book'),
        ),
        migrations.CreateModel(
            name='GenreBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='parser_books.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='parser_books.genre')),
            ],
            options={
                'verbose_name': 'Автор-Книга',
                'verbose_name_plural': 'Авторы-Книги',
            },
        ),
    ]
