# Generated by Django 3.2.16 on 2022-11-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_books', '0002_auto_20221105_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='parser_books.book'),
        ),
    ]
